services:
  - type: web
    name: codev-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
